name: Update README

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update README with public repos
        uses: actions/github-script@v6
        with:
          script: |
            const username = context.repo.owner;
            const { data: repos } = await github.rest.repos.listForUser({
              username,
              per_page: 100,
              sort: 'updated'
            });

            const list = repos.map(r => `- [${r.name}](${r.html_url}) ${r.description ? '— ' + r.description : ''}`).join('\\n');

            const path = 'README.md';
            const { data: readme } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path
            });

            const buff = Buffer.from(readme.content, 'base64').toString();
            const newBuff = buff.replace(/<!-- repo-list-start -->[\\s\\S]*<!-- repo-list-end -->/, `<!-- repo-list-start -->\\n${list}\\n<!-- repo-list-end -->`);

            if (newBuff === buff) {
              console.log('README repo list already up-to-date');
            } else {
              await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path,
                message: 'chore: update repo list',
                content: Buffer.from(newBuff).toString('base64'),
                sha: readme.sha
              });
            }
